### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by motaz** [hatemcode/chatter#11]
I have run the server and it is in waiting for connection state

Server (Chatter) is started .. (2015/03/14 13:10:55)
Server session is started .. (2015/03/14 13:10:55)
Server Host/IP is: Sate40/127.0.1.1 (2015/03/14 13:10:55)
Handling clients .. (2015/03/14 13:10:55)

But when trying to connect in port 5555 in client in the same machine I get connection refused.
I tried localhost and 127.0.0.1

Also could you please expand port server name, and nickname fields a little bit, it is too narrow

**Comment by motaz** [comment]
I works fine now after I changed to 127.0.1.1

**Comment by hatemcode** [comment]
Yeah it is actually listens to one interface , not all of them. But to make sure that your issue is correct not another factors , please provide your case parameters in specific way.

Anyway , I will push a fix , then tell me if that fine !

Thanks

**Comment by hatemcode** [comment]
Well , i pushed that fix. Please test it now again at the same circumstances.

**Comment by motaz** [comment]
Now it work fine. I have tried two clients, Windowns and Linux

**Comment by hatemcode** [comment]
Thanks , I will close the issue right now.
